[players]
all_players = [
    "DeeJTun/adetonanurudeen",
    "Cdq247",
    "Rotawo_69/Bashpopson",
    "iamsqueezy",
    "emmryz_",
    "mista_az/Livingstone",
    "Mrosmoses/Crucial-shocks",
    "charlesnkanga",
    "samlexxxy",
    "brnks4real",
    "Fh3mi",
    "Kelvin_burutu/Vanshergzie",
    "liudeen",
    "Olu_treasure23",
    "sirtobiaminu",
    "iam_officialask"
]


[player_codes]
KolaBilewu = "12w34"
DeeJTun = "r6W2l9Q"
Rotawo_69 = "g7K9r2X"
Cdq247 = "a8M3q6z"
emmryz_ = "p4D7t9b"
brnks4real = "j6L2w5C"
Mrosmoses = "n3V8k1r"
charlesnkanga = "y2Q9f7M"
iamsqueezy = "h5Z3a8T"
samlexxxy = "x7G1p4d"
mista_az = "u9R6c3K"
Stifler_Ldn = "b2T8l5n"
Fh3mi = "c4M9x7R"
Vanshergzie = "v1F6p3h"
sirtobiaminu = "z8L2k5W"
Kelvin_burutu = "e7N3d9Q"
Mr_practus = "m6X5j2P"
Kvng__fuad = "q9T1c7L"
Livingstone = "r3V8z6M"
DhamilolaRappor = "w4K2n9g"
Yusuf_olu = "t8D7h1X"
jamiuAdegboyeg5 = "l2P6f9V"
Crucial-shocks = "k5Q3m8J"
Laycorn12 = "s7N9b4R"
iam_officialask = "f3X2c8T"
thobbi22 = "o1H5v7K"
liudeen = "d9L6r2M"
Bashpopson = "n8Q4p7F"
doctor_nnanna = "j2T5x9H"
AdewaleOlagunju = "m3K7c8V"
Olu_treasure23 = "p5F1g7Z"
Its_Olayinnka = "y8H3n6M"
adetonanurudeen = "c2V9k4D"
iamsholws = "x7R5b1L"
gide__n = "g9Q6m3T"
michael_rich29 = "u4P8n7J"
JoshuaAdaraloye = "a6L2x9F"
steveolatips = "v3D7r8K"
kikz_dami = "z1T5m6C"
Seungrafix = "h8W4q2P"

[links]
link_url = "https://docs.google.com/spreadsheets/d/1-ulIZ5eNjaxR0-m69xLb8XRmHJu-L2bUB9bLUz9iOP8/edit?gid=347270944#gid=347270944"



[Season]
APP_TITLE = "NIUK FC Tournix"
S1 = "https://docs.google.com/spreadsheets/d/1XQ9g5iZVmfOKmnvLWXkyuV9bFtwY3ZIvDhdDMxp5XTk/edit?gid=956052616"
S2 = "https://docs.google.com/spreadsheets/d/15HwiiqVEWI7M41xE3HGeqbGPtihagoC3ERuRSEwsVVM/edit?gid=956052616"
S3 = "https://docs.google.com/spreadsheets/d/1UUaWuyXoAkji_72CEpylPSU39w3Fnwsw1uKYRe9sJcQ/edit?gid=956052616"
S4 = "https://docs.google.com/spreadsheets/d/1-ulIZ5eNjaxR0-m69xLb8XRmHJu-L2bUB9bLUz9iOP8/edit?gid=956052616"


[gcp_service_account]
type = "service_account"
project_id = "psychic-root-396205"
private_key_id = "6e3c137e857e9c032f167fc3927c3108b9dcddb9"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDd2xmJdiazksSP
Aeo0HAcpWG4HFbHPTiVZDjhyYm0F/3Xqc1TSFmJ7LswhEmQ4tXdHDJwqvMl9l4kf
CjhCk1hAWm8FBAkOqJvXkfyFHGSUy5kNT6kgez4N5r61n0NcK5KS5F/h+SI2e0Q9
fhhKH2GL9OXbdnJVn5mC4KG+cTTQQqK6a2Sq/ZCNz6L5NkjhzJJE41SUS8lHBERR
OG05mE+TIIF2AjpcpvuFTFtMefvFW7yYsZcpzmGQpEkvK0ANH29ggxoVSguLysbs
5nAivkRcxKry75q/1mACZ65xONFkvSBMN3GTHaE7c5S48p0Peq3SX4LUguBtLjrj
I32lhFiVAgMBAAECggEAKX3WTRHSg5+VkLxWMZgzU6106HDLgB6YmArzjhrv0mEY
S7h1mtPyZ6DVLvM6WKvBisFmPIzxrwIl9C7sXjEh3mk7XagHTJ1Ghh7IqBlrCzP3
pBhrpEZAUQfAT4Xham3AvCWndALsvd04YjrArq4nR25OBcklcXOHmYVK4qvX6YHP
ltPgWodyDvWDWH1Yc4dj4uisDNw827VR/0x7QS2S12mi8y6VaXlnI9r86SM2MRyF
a/3GNKhh7r/F4x6s2TqMpIh3S0bQ8p1UyDPIifY7AzsrI3DYBADv2rLLpdFjUa+7
j5vAx8McPTTCBd9dhiW9ArhSq1zWZGlWl+Dj/+10KQKBgQD8BZLYJuG2AE6ENBwA
8VrGDEn6xZDxJWGuRoGDxpx3ReIkB/LXbWw2hbhiFs4gdLk81A8UHpPunZd24kNg
IGAxrehjwsvjg98FCQcdwc50UaJKhNCWCFpIXIo7+6BblTr2dxgSVRPIvl7LQK9j
XPNhPWF0gAPhoc51kjYLi/4kTQKBgQDhW5/6uFxGscBWTT3kxeLvqhRAtOHQVi6C
tX41lQhC8r+Q8eZfu4C/R8+mpJS+gtNfaNWzUa/ZkSf97eGtZFxTUZL2Msjs2Gyu
YFKphFwarpkqdmcr7H2FVeM/DjDzBfasXZ6P+a9C10zfbd0NEBF3Bi33cfDLhgAK
98jUPmPJaQKBgE4XIAgwDBJMCAg46VB1eM4TMr0siJvgHGNW33zIhuUCV28Ys2uD
MVu3lYl3TYmLAXbSspVmYCo41Jz2wS/A+G2MWIzI6EpoKyuxP24+Bk3Omb4DZ2qF
zgvL+N1bO7YFCI8kGeZcTFQQgOjz8ySTwaoozdC+dfVtIL8Xff2X9DilAoGAKCVl
c4nCTom95OHvw8CI8/8NipVuoOmpcXmZmTwKc7rA67ZcPvOtNOY7FMm/Ac1WkGmh
oEdOF2kngbIOARCe7ezbTGaxqpfHjKz2LOK6cbpm6MydBpMjrUwmpoYFrFWEoyIu
bCGj2jl2pVryBTC2m8iLCcjPh8JAYbPQoBbZOfkCgYBkkH5Wok3GHfYQjgVMbVf3
wrYosYmf7mQFeeWPnSq/MqjlHhWSL285dk02onAcjgk0NVLUj7zdI0eMrzusbu/A
tMUbcFPGykpBvP0gVCdgg7EsWkVOawfo+Sduoj1vmt63ob+iEpWsnAu2ydiReFrI
/Uktjb3Zc+WmSijsjJvG4w==
-----END PRIVATE KEY-----
"""
client_email = "niuk-ocr-updater@psychic-root-396205.iam.gserviceaccount.com"
client_id = "108756741719934466708"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/niuk-ocr-updater%40psychic-root-396205.iam.gserviceaccount.com"
universe_domain = "googleapis.com"